(define (change-euro amount)
    (cond ((or (< amount 1) (= amount 1)) 0)
        ((or (< amount 2) (= amount 2)) (ce amount 1) )
        ((or (< amount 5) (= amount 5)) (ce amount 2) )
        ((or (< amount 10) (= amount 10)) (ce amount 3) )
        ((or (< amount 20) (= amount 20)) (ce amount 4) )
        ((or (< amount 50) (= amount 50)) (ce amount 5) )
        ((or (< amount 100) (= amount 100)) (ce amount 6) )
        ((or (< amount 200) (= amount 200)) (ce amount 7) )
        (else (ce amount 8))
    ))
(define (ce amount coin)
    (cond ((or (< amount 0) (= coin 0)) 0)
        ((= amount 0) 1)
        (else (+ (ce amount (- coin 1)) (ce (- amount (coin-value coin)) coin)))
    ))
(define (coin-value coin)
    (cond ((= coin 1) 1)
        ((= coin 2) 2)
        ((= coin 3) 5)
        ((= coin 4) 10)
        ((= coin 5) 20)
        ((= coin 6) 50)
        ((= coin 7) 100)
        ((= coin 8) 200)
    ))
(display "change-euro 0 -> ") (display (change-euro 0))
(newline)
(display "change-euro 1 -> ") (display (change-euro 1))
(newline)
(display "change-euro 2 -> ") (display (change-euro 2))
(newline)
(display "change-euro 3 -> ") (display (change-euro 3))
(newline)
(display "change-euro 5 -> ") (display (change-euro 5))
(newline)
(display "change-euro 6 -> ") (display (change-euro 6))
(newline)
(display "change-euro 9 -> ") (display (change-euro 9))
(newline)
(display "change-euro 10 -> ") (display (change-euro 10))
(newline)
(display "change-euro 14 -> ") (display (change-euro 14))
(newline)
(display "change-euro 15 -> ") (display (change-euro 15))
(newline)
(display "change-euro 20 -> ") (display (change-euro 20))
(newline)
(display "change-euro 25 -> ") (display (change-euro 25))
(newline)
(display "change-euro 50 -> ") (display (change-euro 50))
(newline)
;(display "change-euro 100 -> ") (display (change-euro 100))
(newline)
;(display "change-euro 200 -> ") (display (change-euro 200))
(newline)
;(display "change-euro 300 -> ") (display (change-euro 300))
(newline)
;(display "change-euro 500 -> ") (display (change-euro 500))
(newline)
(exit)