(define (square x) (* x x))
(define (plussquare x y) (+ (square x) (square y)))
(define (sum-of-sq-2-lg x y z)
    (cond ((and (> x z) (> y z)) (plussquare x y))
            ((and (> x z) (> z y)) (plussquare x z))
            ((and (> x y) (> y z)) (plussquare x y))
            ((and (> x y) (> z y)) (plussquare x z))
            ((and (> y x) (> z x)) (plussquare y z))))
(display "3 1 2 -> ") (display (sum-of-sq-2-lg 3 1 2))
(newline)
(display "1 3 2 -> ") (display (sum-of-sq-2-lg 1 3 2))
(newline)
(display "1 2 3 -> ") (display (sum-of-sq-2-lg 1 2 3))
(newline)
(display "3 2 1 -> ") (display (sum-of-sq-2-lg 3 2 1))
(newline)
(display "2 3 1 -> ") (display (sum-of-sq-2-lg 2 3 1))
(newline)
(display "2 1 3 -> ") (display (sum-of-sq-2-lg 2 1 3))
(newline)
(exit)