(define (exp a n)
    (define (exp-iter a n counter accum)
        (if (= counter n) accum (exp-iter a n (+ counter 1) (* accum a))))
    (exp-iter a n 0 1))
(newline)
(display "exp 3 2 -> ") (display (exp 3 2))
(newline)
(display "exp 2 8 -> ") (display (exp 2 8))
(newline)
(display "exp 4 5 -> ") (display (exp 4 5))
(exit)