(define (fiborec n)
    (cond ((= n 0) 0)
        ((= n 1) 1)
        (else (+ (fiborec (- n 1)) (fiborec (- n 2))))))
(display "fiborec 0 -> ") (display (fiborec 0))
(newline)
(display "fiborec 1 -> ") (display (fiborec 1))
(newline)
(display "fiborec 2 -> ") (display (fiborec 2))
(newline)
(display "fiborec 3 -> ") (display (fiborec 3))
(newline)
(display "fiborec 4 -> ") (display (fiborec 4))
(newline)
(display "fiborec 5 -> ") (display (fiborec 5))
(newline)
(display "fiborec 6 -> ") (display (fiborec 6))
(newline)
(display "fiborec 32 -> ") (display (fiborec 32))
(newline)
(exit)