(define (abs x)
    (if (< x 0) (- x) x))
(define (square x) 
    (* x x))
(define (sqrtapprox guess n) 
    (if (< (abs (- (square guess) n)) 0.01) guess (sqrtapprox (/ (+ guess (/ n guess)) 2) n)))
(define (sqrt n)
    (sqrtapprox (/ n 2) n))
(display "sqrt(9) -> ")
(display (sqrt 9))
(newline)
(display "sqrt(8) -> ")
(display (sqrt 8))
(newline)
(display "sqrt(16) -> ")
(display (sqrt 16))
(newline)
(display "sqrt(25) -> ")
(display (sqrt 25))
(newline)
(display "sqrt(100) -> ")
(display (sqrt 100))
(newline)
(display "sqrt(1024) -> ")
(display (sqrt 1024))
(newline)
(display "sqrt(256) -> ")
(display (sqrt 256))
(newline)
(exit)